### ISSUE TITLE
horizontal

### ISSUE THREAD

**Issue by obobo3** [hrshadhin/conky-crypto-coins#3]
hey,
can you make it horizontal? i mean horizontal row.

**Comment by hrshadhin** [comment]
You mean like this?
![demo](https://image.ibb.co/j0u5ao/p1.png)

**Comment by obobo3** [comment]
ye, but horizontal, nvm, made it, thnx

**Comment by hrshadhin** [comment]
sorry, i made a mistake.

> nvm, made it,

what do you mean?

**Comment by obobo3** [comment]
i mean nevermind, i did it horizontal

`conky.config = {

-------------------------------------
--  Generic Settings
-------------------------------------
background=false,
update_interval=1,
double_buffer=true,
no_buffers=true,


draw_shades=false,
draw_outline=false,
draw_borders=false,
draw_graph_borders=false,
default_graph_height=26,
default_graph_width=80,
show_graph_scale=false,
show_graph_range=false,


-------------------------------------
--  Window Specifications
-----------------------------------
gap_x=1450,
gap_y=940,
minimum_height=145,
minimum_width=636,
own_window=true,
own_window_type="normal",
own_window_transparent=true,
own_window_transparent=true,
own_window_argb_visual=true,
own_window_argb_value=50,
own_window_hints="undecorated,below,sticky,skip_taskbar,skip_pager",
border_inner_margin=0,
border_outer_margin=0,
--alignment="middle_middle",
--own_window_argb_visual=true,
--own_window_argb_value=0,


-------------------------------------
--  Text Settings
-------------------------------------
use_xft=true,
xftalpha=1,
font="Droid Sans:size=10",
text_buffer_size=256,
override_utf8_locale=true,


-------------------------------------
--  Color Scheme
-------------------------------------
default_color="FFFFFF",
color1="FFFFFF",
color2="FFFFFF",





}



conky.text = [[
\
\
${execi 300  curl -s "https://api.coinmarketcap.com/v1/ticker/" -o ~/conky-crypto-coins/rates.json}\
\
\
\
\
\
\
\
\
${color2}${voffset 50}${alignc 260}BTC
${color2}${voffset -17}${alignc 184}ETH
${color2}${voffset -17}${alignc 108}LTC
${color2}${voffset -17}${alignc 32}XMR
${color2}${voffset -17}${alignc -44}EOS
${color2}${voffset -17}${alignc -120}DASH
\
\
\
\
${color2}${voffset 53}${alignc 260}${execi 0 cat ~/conky-crypto-coins/rates.json | jq -r '.[] | select(.symbol == "BTC") | .price_usd' | awk '{print "$"$1}'}
${color2}${voffset -17}${alignc 184}${execi 0 cat ~/conky-crypto-coins/rates.json | jq -r '.[] | select(.symbol == "ETH") | .price_usd' | awk '{print "$"$1}'}
${color2}${voffset -17}${alignc 108}${execi 0 cat ~/conky-crypto-coins/rates.json | jq -r '.[] | select(.symbol == "LTC") | .price_usd' | awk '{print "$"$1}'}
${image ~/conky-crypto-coins/images/btc.png -p 42,75 -s 32x32}\
${image ~/conky-crypto-coins/images/eth.png -p 118,75 -s 32x32}\
${image ~/conky-crypto-coins/images/ltc.png -p 194,75 -s 32x32}${font}\
\
\
\
\
\
\
\
\
${color2}${voffset -17}${alignc 32}${execi 0 cat ~/conky-crypto-coins/rates.json | jq -r '.[] | select(.symbol == "XMR") | .price_usd' | awk '{print "$"$1}'}
${color2}${voffset -17}${alignc -44}${execi 0 cat ~/conky-crypto-coins/rates.json | jq -r '.[] | select(.symbol == "EOS") | .price_usd' | awk '{print "$"$1}'}
${color2}${voffset -17}${alignc -120}${execi 0 cat ~/conky-crypto-coins/rates.json | jq -r '.[] | select(.symbol == "DASH") | .price_usd' | awk '{print "$"$1}'}
${image ~/conky-crypto-coins/images/xmr.png -p 270,75 -s 32x32}\
${image ~/conky-crypto-coins/images/eos.png -p 346,75 -s 32x32}\
${image ~/conky-crypto-coins/images/dash.png -p 422,75 -s 32x32}${font}\
]]
`
thnx for config, bud.

**Comment by hrshadhin** [comment]
Can you share the full codes and images? If yes, please give a pull request.
